name: 2. Production Manual Deploy
on:
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Prod Docker Image
        run: sudo docker build -t virt-site:${{ github.sha }} .

      - name: Import Image to Kubernetes (K3s)
        run: sudo docker save virt-site:${{ github.sha }} | sudo k3s ctr images import -

      - name: Update Image Tag in YAML
        run: sed -i "s/virt-site:latest/virt-site:${{ github.sha }}/g" k8s/prod-deployment.yaml

      - name: Apply Prod Deployment
        run: sudo k3s kubectl apply -f k8s/prod-deployment.yaml