name: 1. QA Auto Deploy
on:
  push:
    branches: [ main, master ]

jobs:
  deploy-qa:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build QA Docker Image
        run: sudo docker build -t virt-qa-site:${{ github.sha }} .

      - name: Import Image to Kubernetes (K3s)
        run: sudo docker save virt-qa-site:${{ github.sha }} | sudo k3s ctr images import -

      - name: Update Image Tag in YAML
        run: sed -i "s/virt-qa-site:latest/virt-qa-site:${{ github.sha }}/g" k8s/qa-deployment.yaml

      - name: Apply QA Deployment
        run: sudo k3s kubectl apply -f k8s/qa-deployment.yaml